modules/reports/controllers/MainController.php
<?php

namespace app\modules\reports\controllers;

use app\modules\reports\models\ReportsTree;
use app\modules\reports\models\SearchRepositoryFiles;
use yii\data\ArrayDataProvider;
use yii\web\Controller;
use dosamigos\arrayquery\ArrayQuery;
use yii\helpers\Html;
use yii\helpers\Url;
use Yii;

/**
 * Default controller for module 'Reports'
 */
class MainController extends Controller
{

    public $defaultAction = 'list';
    public static $nestedFolders; //array of nested folders
    public static $relationArray;
    public static $modalContentUri = 'folder/move-files'; //uri for content into Modal (click Massive move button)

    public function init()
    {
        self::$relationArray = [];
    }

    /**
     * @var array list of items (folder, files) and options for menu (New)
     * - icon: icon's style
     * - label: string, optional, specifies the menu item label.
     * - urlNew: array, optional, specifies the URL for creating new item. It will be processed by [[Url::to]].
     */
    public $entities = [
        'userFolder' => [
            'icon' => 'fa fa-folder',
            'label' => 'User Folder',
            'urlNew' => ['folder/create', 'type' => 'userFolder'],
        ],
        'folder' => [
            'icon' => 'fa fa-folder-o',
            'label' => 'Folder',
            'urlNew' => ['folder/create'],
        ],
        'pdf' => [
            'icon' => 'fa fa fa-file-pdf-o',
            'label' => 'Pdf',
            'urlNew' => ['document/create', 'type' => 'pdf'],
        ],
        'movie' => [
            'icon' => 'fa fa-file-movie-o',
            'label' => 'Movie',
            'urlNew' => ['document/create', 'type' => 'movie'],
        ],
        'html5' => [
            'icon' => 'fa fa-file-code-o',
            'label' => 'HTML5',
            'urlNew' => ['document/create', 'type' => 'html5'],
        ],
        'gallery' => [
            'icon' => 'fa fa-file-image-o',
            'label' => 'gallery',
            'urlNew' => ['document/create', 'type' => 'gallery'],
        ],
        'powerpoint' => [
            'icon' => 'fa fa-file-powerpoint-o',
            'label' => 'PowerPoint',
            'urlNew' => ['document/create', 'type' => 'powerpoint'],
        ],
        'excel' => [
            'icon' => 'fa fa-file-excel-o',
            'label' => 'Excel',
            'urlNew' => ['document/create', 'type' => 'excel'],
        ],
        'word' => [
            'icon' => 'fa fa-file-word-o',
            'label' => 'Word',
            'urlNew' => ['document/create', 'type' => 'word'],
        ],
        'default' => [
            'icon' => 'fa fa-file',
            'label' => 'File',
            'urlNew' => ['document/create', 'type' => 'file'],
        ],
    ];

    /**
     * Constuct list datatable
     * @return type
     */
    public function actionList()
    {
        $modelsProvider = [];
        
        $newEntities = false; //block new button by default

        if (Yii::$app->getRequest()->getQueryParam('sharable') || Yii::$app->getRequest()->getQueryParam('type')) { //apply filters
            $itemsList = $this->buildNestedList(); //nested list (before apply filters)
            $modelsProvider = $this->applyFilters($itemsList, Yii::$app->getRequest()->getQueryParams());
        } else { //get array of nested folders and medias (default action (without filters))
            $folderId = (Yii::$app->getRequest()->getQueryParam('id_folder')) ? Yii::$app->getRequest()->getQueryParam('id_folder') : null;
            $currentFolder = (!is_null($folderId)) ? ReportsTree::findOne(['id_report_tree' => $folderId]) : null; //for one folder in root
            $modelsProvider = $this->getFolderContent($currentFolder);
            $newEntities = $this->parseNewEntities($currentFolder);
        }

        $provider = new ArrayDataProvider([
            'allModels' => $modelsProvider,
            'sort' => [
                'attributes' => ['icon', 'name', 'type', 'sharable', 'size'],
            ],
        ]);


        return $this->render('list', [
            'folder' => isset($currentFolder) ? $currentFolder : false,
            'newEntities' => $newEntities,//isset($currentFolder) ? $this->parseNewEntities($currentFolder) : $this->parseNewEntities(), //items for dropdown list (button NEW) -> only inside folder!!!
            'dataProvider' => $provider,
        ]);
    }

    /**
     * build Folders
     * @return type
     */
    public function actionFolders()
    {
        $roots = ReportsTree::find()->roots()->all();

        self::$nestedFolders = [];
        
        foreach ($roots as $rootFolder) {
            self::$nestedFolders[$rootFolder->id_report_tree] = ['label' => '<span class="label h-bg-navy-blue"><i class="fa fa-folder"></i></span> ' . $rootFolder->label.self::setUserFolderBtn($rootFolder->id_report_tree), 'options' => ['data-id' => $rootFolder->id_report_tree]]; //['label' => $rootFolder->label, 'options' => ['data-id' => $rootFolder->id_folder]];

            foreach (SearchRepositoryFiles::$typeRelations as $type => $params) {
                $typeId = "type_{$rootFolder->id_report_tree}_{$type}";
                self::setArray(self::$nestedFolders, "{$rootFolder->id_report_tree}.items.{$typeId}", ['label' => '<span class="label h-bg-navy-blue"><i class="' . $params['icon'] . '"></i></span> ' . $params['label'] . self::setMassiveMoveBtn($rootFolder->id_report_tree, $type, $params['label']), 'options' => ['data-id' => $typeId]]);
            }
            //build recursively nested folder's structure
            Yii::trace('folders nested begin:' . print_r(self::$nestedFolders, true));
            self::folderNestedRecursive($rootFolder->children(1)->all(), "{$rootFolder->id_report_tree}"); //true|false
        }
        
        return $this->render('folders', [
            'folders' => self::$nestedFolders,
            'newEntities' => false, //items for dropdown list (button NEW)
        ]);
    }

    /**
     * Build flow
     * @param type $id_folder
     * @return type
     */
    public function actionFlow($id_folder = null)
    {
        $currentFolder = (!is_null($id_folder)) ? ReportsTree::findOne(['id_report_tree' => $id_folder]) : null;
        $items = $this->getFolderContent($currentFolder, 'text-info');
        return $this->render('flow', [
            'folder' => $currentFolder,
            'columns' => $this->buildFlowGrid($items),
            'newEntities' => false,//$this->parseNewEntities($currentFolder), //items for dropdown list (button NEW)
        ]);
    }

    /**
     * Search by media's or folder's title for actionFolders() and actionFlow()
     * @return type
     */
    public function actionSearch()
    {

        $modelsProvider = [];
        $itemsList = $this->buildNestedList(); //nested list (before apply filters)
        $modelsProvider = $this->applyFilters($itemsList, Yii::$app->request->post());

        $provider = new ArrayDataProvider([
            'allModels' => $modelsProvider,
            'sort' => [
                'attributes' => ['icon', 'name', 'type', 'sharable', 'size'],
            ],
        ]);

        return $this->renderAjax('searchList', [
            'dataProvider' => $provider,
        ]);
    }

    /**
     * Get content for current folder (multiple root available)
     * @param type $folder ReportsTreeObject | null
     * @param type $addIconStyle additional style name
     * @return array
     */
    public function getFolderContent($folder = null, $addIconStyle = null)
    {
        $output = []; //models array for provider (first - folder, then - media for current folder)
        // select root folders
        if (is_null($folder))
            $folders = ReportsTree::find()->roots()->all();
        //select first level children folders
        else
            $folders = $folder->children(1)->all();

        foreach ($folders as $subfolder) {
            $output[] = $this->parseFolder($subfolder, $addIconStyle);
        }

        if (!is_null($folder)) { // set media list for current folder 
            foreach ($folder->media as $media) {
                $output[] = $this->parseMedia($media, $addIconStyle);
            }
        }

        return $output;
    }

    /**
     * Build nested list of folders/subfolders/medias
     * include only unique media (removed the duplicate medias)
     * @return array
     */
    public function buildNestedList()
    {
        $output = [];
        $roots = ReportsTree::find()->roots()->all();
        foreach ($roots as $folder) {
            $output[] = $this->parseFolder($folder);
            foreach ($folder->media as $media) {
                if ($this->mediaAlreadyExists($output, "id", $media->id_media, $media->type))
                    continue; //if media allready in array (earlier added from another linked folder)

                $output[] = $this->parseMedia($media);
            }
            foreach ($folder->children()->all() as $subfolder) {
                $output[] = $this->parseFolder($subfolder);
                foreach ($subfolder->media as $mediaSub) {
                    if ($this->mediaAlreadyExists($output, "id", $mediaSub->id_media, $mediaSub->type))
                        continue; //if media allready in array (earlier added from another linked folder)

                    $output[] = $this->parseMedia($mediaSub);
                }
            }
        }
        return $output;
    }

    /**
     * Apply filters for list of items (folders/subfolders/medias)
     * @param type $input array of items (folders/subfolders/medias)
     * @param type $getParams array of filter params
     * @return type
     */
    public function applyFilters($input, $getParams)
    {
        if (count($input) == 0)
            return $input; //don't apply filter to empty array

        $output = $input;

        if (isset($getParams['sharable'])) {
            $querySharable = new ArrayQuery($output);

modules/reports/views/main/_menu.php
<div class="panel-body">
    <div class="dropdown">
        <a class="dropdown-toggle btn btn-success btn-block <?php if(!$this->params['newEntities']) echo 'disabled'; ?>" href="#" data-toggle="dropdown">
            NEW
        </a>

        <?php
        echo yii\widgets\Menu::widget([
            'encodeLabels' => false,
            'options' => [
                'class' => 'dropdown-menu filedropdown m-l',
            ],
            'items' => ($this->params['newEntities']) ? $this->params['newEntities'] : [],
        ]);
        ?>
    </div>

    <?php echo yii\bootstrap\Nav::widget([
        'options' => ['class' => 'h-list m-t'],
        'encodeLabels' => false,
        'items' => [
            [
                'label' => '<i class="fa fa-list"></i> List',
                'url' => ['main/list'],
            ],
            [
                'label' => '<i class="fa fa-folder"></i> Folders',
                'url' => ['main/folders'],
            ],
            [
                'label' => '<i class="fa fa fa-th"></i> Flow',
                'url' => ['main/flow'],
            ]
        ],
    ]);
    ?>
</div>

modules/reports/views/main/_searchForm.php
<div class="input-group">
    <input class="form-control" name="search" id="search" type="text" placeholder="Search Documents.." value="">
    <div class="input-group-btn">
        <button class="btn btn-default" id="searchButton"><i class="fa fa-search"></i></button>
    </div>
</div>

<?php
$script = <<<EOD
//$('#searchButton').click(function(){
$("#search").on("input",function(e){
//console.log($('#search').val());
    $.ajax({
        url:'search',
        type:'POST',
        data:'search='+$("#search").val(),
        dataType: 'html',
        success:function(data){
            $('#body-result').html(data);
        }
    });
});

EOD;
$this->registerJs($script, \yii\web\View::POS_READY);

modules/reports/views/main/flow.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = 'Flow views';

// module root
$this->params['breadcrumbs'][] = [
    'label' => "Reports",
    'url' => ['']
];


if (isset($folder['id_report_tree']) && $folder['id_report_tree'] > 0) {
    $this->params['breadcrumbs'][] = ['label' => $this->title, 'url' => ['main/flow']];

    $parents = $folder->parents()->all();
    foreach ($parents as $parentFolder) {
        $this->params['breadcrumbs'][] = [
            'label' => $parentFolder->label,
            'url' => ['main/flow', 'id_folder' => $parentFolder->id_report_tree]
        ];
    }

    $this->params['breadcrumbs'][] = [
        'label' => $folder['label'],
        'template' => "<li><b>{link}</b></li>\n"
    ];
} else {
    $this->params['breadcrumbs'][] = $this->title;
}


$this->params['headerTitle'] = "Reports Flow View";
$this->params['headerDescription'] = "Use Reports view to show all documents in a tree .";

$this->params['newEntities'] = $newEntities; // for dropdown list on click button NEW
?>

<div class="col-md-3">
    <div class="hpanel">
        <?=
        $this->render(
            '_menu.php'
        )
        ?>
    </div>
</div>

<div class="col-md-9">
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel">
                <div class="panel-body">
                    <?= $this->render(
                        '_searchForm.php'
                    ) ?>
                </div>
            </div>
        </div>
    </div>

    <div class="row" id="body-result">
        <?php if (count($columns) > 0): ?>
            <?php foreach ($columns as $column): ?>
                <div class="col-md-3">
                    <?php foreach ($column as $object): ?>
                        <div class="hpanel">
                            <div class="panel-body file-body">
                                <?php
                                if (in_array($object['type'], ['folder','userFolder'])) $uri = 'folder';
                                else $uri = 'document';
                                echo Html::a(
                                    $object['icon'],
                                    [$uri . '/view', 'id' => $object['id']]
                                );
                                ?>
                            </div>
                            <div class="panel-footer">
                                <?php
                                if (in_array($object['type'], ['folder','userFolder'])) {
                                    echo Html::a(
                                        $object['name'],
                                        ['main/flow', 'id_folder' => $object['id']],
                                        ['style' => 'text-decoration:underline;']
                                    );
                                } else {
                                    if (isset($object['repFile'])) {
                                        echo Html::a(
                                            $object['name'],
                                            ['/uploads/' . $object['repFile']],
                                            ['style' => 'text-decoration:underline;']
                                        );
                                    } else {
                                        echo Html::tag('span', $object['name']);
                                    }
                                }

                                ?>

                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endforeach; ?>
        <?php else: ?>
            <div class="col-md-3">
                <div class="hpanel">
                    <strong>Empty folder</strong>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>

modules/reports/views/main/folders.php
<?php

$this->title = 'Folders views';

// module root
$this->params['breadcrumbs'][] = [
    'label' => "Reports",
    'url' => ['main/list']
];

$this->params['breadcrumbs'][] = $this->title;


$this->params['headerTitle'] = "Reports Folders View";
$this->params['headerDescription'] = "Use Folders view to show all documents in a tree .";

$this->params['newEntities'] = $newEntities; // for dropdown list on click button NEW


?>

    <div class="col-md-3">
        <div class="hpanel">
            <?=
            $this->render(
                '_menu.php'
            )
            ?>
        </div>
    </div>

    <div class="col-md-9">
        <div class="row">
            <div class="col-lg-12">
                <div class="hpanel">
                    <div class="panel-body">
                        <?= $this->render(
                            '_searchForm.php'
                        ) ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="row" id="body-result">
            <div class="hpanel">
                <div class="panel-heading hbuilt">
                    <div id="nestable-menu" class="pull-right">
                        <button type="button" data-action="expand-all" class="btn btn-default btn-xs">Expand All
                        </button>
                        <button type="button" data-action="collapse-all" class="btn btn-default btn-xs">Collapse All
                        </button>
                    </div>
                    Document Folders
                </div>


                <div class="panel-body">
                    <div class="dd" id="nestableFolders">
                        <?php
                        echo yii\widgets\Menu::widget([
                            'options' => ['class' => 'dd-list', 'tag' => 'ol'],
                            'encodeLabels' => false,
                            'submenuTemplate' => "\n<ol 'class'='dd-list'>\n{items}\n</ol>\n",
                            'labelTemplate' => "<div class='dd-nodrag'>{label}</div>",
                            'items' => $folders,
                            'itemOptions' => ['class' => 'dd-item'],
                        ]);
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>


<?php
$this->registerJsFile(Yii::$app->request->baseUrl . '/js/reports/folders_nestable.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile(Yii::$app->request->baseUrl . '/js/reports/ajax-modal-popup.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile(Yii::$app->request->baseUrl . '/js/reports/ajax-move-files.js', ['depends' => [\yii\web\JqueryAsset::className()]]);

$this->registerCssFile("/homer/js/lou-multi-select-05449b3/css/multi-select.css", [
    'depends' => [\yii\bootstrap\BootstrapAsset::className()],
]);
$this->registerJsFile(Yii::$app->request->baseUrl . '/homer/js/quicksearch/jquery.quicksearch.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile(Yii::$app->request->baseUrl . '/homer/js/lou-multi-select-05449b3/js/jquery.multi-select.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
?>

modules/reports/views/main/list.php
<?php

use yii\helpers\Html;
use app\components\DataTablesEmptyBody;
//use fedemotta\datatables\DataTables;


$this->title = 'List views';

// module root
$this->params['breadcrumbs'][] = [
    'label' => "Reports",
    'url' => ['']
];


if (isset($folder['id_report_tree']) && $folder['id_report_tree'] > 0) {
    $this->params['breadcrumbs'][] = ['label' => $this->title, 'url' => ['main/list']];

    $parents = $folder->parents()->all();
    foreach ($parents as $parentFolder) {
        $this->params['breadcrumbs'][] = [
            'label' => $parentFolder->label,
            'url' => ['main/list', 'id_folder' => $parentFolder->id_report_tree]
        ];
    }

    $this->params['breadcrumbs'][] = [
        'label' => $folder['label'],
        'template' => "<li><b>{link}</b></li>\n"
    ];
} else {
    $this->params['breadcrumbs'][] = $this->title;
}

$this->params['headerTitle'] = "Reports List View";
$this->params['headerDescription'] = "Use List view to show only Reports in a sortable list.";

$this->params['newEntities'] = $newEntities; // for dropdown list on click button NEW

//$searchModel = new app\modules\documents\models\MediaFolderSearch();//for testing
//$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
?>

<div class="col-md-3">
    <div class="hpanel">
        <?= $this->render(
            '_menu'
        ) ?>
    </div>
    <div class="hpanel">
        <div class="panel-body">
            <div class="m-b-md">
                <h4>
                    Filters
                </h4>
                <small>
                    Filter your data based on different options below.
                </small>
            </div>

            <?= Html::beginForm(['main/list'], 'GET', ['id' => 'filter-form']); ?>
            <div class="form-group">
                <label class="control-label">Type:</label>

                <div class="input-group">
                    <?= Html::dropDownList('type', (Yii::$app->getRequest()->getQueryParam('type')) ? Yii::$app->getRequest()->getQueryParam('type') : '---',
                        [
                            'all' => 'All',
                            'files' => 'Files',
                            'folders' => 'Folders',
                            'userFolders' => 'User Folders',
                            '---' => '---',
                            'pdf' => 'Pdf',
                            'movie' => 'Movie',
                            'html5' => 'Html5',
                            'gallery' => 'Gallery',
                            'powerpoint' => 'Powerpoint',
                            'excel' => 'Excel',
                            'word' => 'Word',
                        ],
                        [
                            'class' => 'form-control m-b',
                        ]); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label">Status:</label>

                <div class="input-group">
                    <div class="checkbox checkbox-primary">
                        <?= Html::checkbox(
                            'sharable',
                            (Yii::$app->getRequest()->getQueryParam('sharable')) ? true : false,
                            ['id' => 'sharable']) ?>
                        <label for="sharable">
                            Sharable
                        </label>
                    </div>
                </div>
            </div>

            <?= Html::submitButton('Apply', ['class' => 'btn btn-success btn-block']); ?>

            <?= Html::endForm(); ?>

        </div>
    </div>

</div>

<div class="col-md-9">
    <div class="hpanel">
        <div class="panel-heading">
            <div class="panel-tools">
                <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                <a class="closebox"><i class="fa fa-times"></i></a>
            </div>
            Standard table
        </div>

        <div class="panel-body">
            <?php
            /*
            $searchModel = new ModelSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
            */
            ?>
            <?= DataTablesEmptyBody::widget([
                'dataProvider' => $dataProvider,
                'formatter' => ['class' => 'yii\i18n\Formatter','nullDisplay' => ''],
                'tableOptions' => [
                    'class' => 'table table-striped table-bordered table-hover dataTable no-footer',
                ],
                'clientOptions' => [
                    'dom' => 'lftrip',
                    'searching' => true,
                    'paging' => true,
                    'aaSorting' => [],
                    'language' => [
                        "search" => "Search:",
                        "emptyTable" => "No matching records found",
                    ],
                    /*'columns' => [
                        null,
                        null,
                        null,
                        null,
                        [
                           'orderable'=>false //https://datatables.net/reference/option/columns.orderable
                        ]],
                    */
                    'columnDefs' => [
                        [
                            "type" => "num-html", "targets" => 0
                        ],
                        [
                            "type" => "num-html", "targets" => 3
                        ],
                        [
                            "type" => "file-size",
                            //"orderable"=> false,
                            "targets" => 4
                        ],
                        [
                            "orderable" => false,
                            "targets" => -1
                        ]
                    ]
                ],
                //'filterModel' => $searchModel,
                'columns' => [
                    [
                        'attribute' => 'icon',
                        'format' => 'html',
                        'value' => function ($model) {
                            return $model['icon'];
                            //return Html::img(Yii::getAlias('@web').'/images/'. $data['image'], ['width' => '70px']); //for images instead icons
                        }
                    ],

                    [

                        //'header' => '<span class="glyphicon glyphicon-user"></span>',
                        'attribute' => 'name',
                        'format' => 'html',
                        'value' => function ($model) {
                            if (in_array($model['type'], ['folder','userFolder'])) return Html::a($model['name'], ['list', 'id_folder' => $model['id']], ['class' => 'list-link']); 
                            else return $model['name'];
                        }
                    ],
                    [
                        'attribute' => 'type',
                        'value' => function ($model) {
                            if ($model['type'] == 'userFolder') return 'User Folder'; 
                            else return $model['type'];
                        } 
                    ],
                    [
                        'attribute' => 'sharable',
                        'format' => 'html',
                        'value' => function ($model) {
                            switch ($model['sharable']) {
                                case 0:
                                    return '<i class="fa fa-square-o"></i>';
                                    break;
                                case 1:
                                    return '<i class="fa fa-check-square-o"></i>';
                                    break;
                                case 2:
                                    return '<i class="fa fa-minus-square-o"></i>';
                                    break;
                            }
                        }
                    ],
                    [
                        'attribute' => 'size',
                        'value' => function ($model) {
                            return  Yii::$app->formatter->asShortSize($model['size'], 2);//($model['size']) ?  $model['size']. ' b' : '0 b'; 
                        }
                    ],
                    'pattern',
                    [
                        'header' => 'Actions',
                        'headerOptions' => ['class' => ''],
                        'class' => 'yii\grid\ActionColumn',
                        'template' => '{rootFolder} {download} {view} {update} {delete}',
                        'buttons' => [
                            'rootFolder' => function ($url, $model) {
                                return ($model['type'] == 'userFolder') ? Html::a('<span class="fa fa-user"></span>', ['folder/update', 'id' => $model['id'], 'tab' => 'users']) : '';  
                            },
                            'view' => function ($url, $model) {
                                if (in_array($model['type'],['folder','userFolder'])) $uri = 'folder';
                                else $uri = 'document';
                                return Html::a(
                                    '<span class="fa fa-eye"></span>',
                                    [$uri . '/view', 'id' => $model['id']]
                                );
                            },
                            'update' => function ($url, $model) {
                                if (in_array($model['type'],['folder','userFolder'])) $uri = 'folder';
                                else $uri = 'document';
                                return Html::a(
                                    '<span class="fa fa-pencil"></span>',
                                    [$uri . '/update', 'id' => $model['id']]
                                );
                            },
                            'download' => function ($url, $model) {
                                if (in_array($model['type'],['folder','userFolder'])) return Html::tag('span', '', ['class' => "fa fa-download"]);
                                else {
                                    if (isset($model['repFile'])) {
                                        return Html::a(
                                            '<span class="fa fa-download"></span>',
                                            ['/uploads/' . $model['repFile']]
                                        );
                                    }
                                    return Html::tag('span', '', ['class' => "fa fa-download"]);
                                }

                            },
                            'delete' => function ($url, $model) {
                                if (in_array($model['type'],['folder','userFolder'])) $uri = 'folder';
                                else $uri = 'document';
                                return Html::a(
                                    '<span class="fa fa-trash"></span>',
                                    [$uri . '/delete', 'id' => $model['id']]
                                );
                            },
                        ],
                    ],
                ],

            ]); ?>
        </div>


    </div>


</div>