modules/documents/controllers/FolderController.php
<?php

namespace app\modules\documents\controllers;

use app\modules\documents\models\DocsTree;
use app\modules\documents\models\Media;
use app\modules\documents\models\MediaLinks;
use app\modules\documents\models\DocsTreeTr;
use app\modules\documents\models\SearchRepositoryFiles;

use yii\data\ActiveDataProvider;
use Yii;

/**
 * Controller for actions with folder
 */
class FolderController extends \yii\web\Controller
{

    /**
     * View information about this folder
     * @param type $id
     * @return type
     */
    public function actionView($id)
    {
        $model = DocsTree::findOne($id);

        // data provider for Media in this folder
        $dataProviderMedia = new ActiveDataProvider([
            'query' => Media::find()
                ->joinWith('mediaLinks.folder')
                ->where(['zse_v1_media_links.id_container' => $id])
                ->groupBy('zse_v1_media.id_media'),
            'sort' => [
                'attributes' => ['name', 'type', 'sharable', 'size']
            ]
        ]);

        // data provider for translation this folder
        $dataProviderTranslation = new ActiveDataProvider([
            'query' => DocsTreeTr::find()
                ->joinWith('docsTree')
                ->where(['zse_v1_docs_tree_tr.id_folder' => $id]),
            'sort' => [
                'attributes' => [
                    'label',
                    'lang',
                    'description'
                ]
            ],
        ]);

        $folderTranslations = $this->buildTranslationArray($model); // translation for this folder

        return $this->render('view', [
            'model' => $model,
            'dataProviderMedia' => $dataProviderMedia,
            'folderTranslations' => $folderTranslations,
        ]);
    }

    /**
     * Create folder
     */
    public function actionCreate()
    {
        Yii::trace("GET params begin create = ".print_r(Yii::$app->request->queryParams,true));

        if (!Yii::$app->getRequest()->getQueryParam('id_folder')) {
            return $this->redirect(['main/list']);
        }
        $idContainer = Yii::$app->getRequest()->getQueryParam('id_folder');

        Yii::trace("POST Data:" . print_r(Yii::$app->request->post(), true));

        $folder = new DocsTree();
        $folder->icon = ''; // standard icon by default
        $folder->scenario = 'create';

        if ($folder->load(Yii::$app->request->post())) {
            if ($folder->validate()) {
                // save nested folder
                $parentFolder = DocsTree::findOne(['id_folder' => $idContainer]);
                $folder->appendTo($parentFolder);
                //$folder->save(false);

                return $this->redirect(['update', 'id' => $folder->getPrimaryKey()]);
            } else {
                $errors['folder'] = $folder->errors;
                Yii::trace("Errors when save files: " . print_r($errors, true));
            }
        }


        $folderTranslations = $this->buildTranslationArray($folder); // translation for this folder

        return $this->render('create', [
            'model' => $folder,
            'idContainer' => $idContainer,
            'folderTranslations' => $folderTranslations
        ]);
    }

    /**
     * Update existing model Media
     * @param $id
     * @return string|\yii\web\Response
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $model->scenario = 'create';

        $folderTranslations = $this->buildTranslationArray($model); // translation for this folder

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['update', 'id' => $model->id_folder]);
        }


        $folderParent = $model->parents(1)->one();

        return $this->render('create', [
            'model' => $model,
            'idContainer' => ($folderParent) ? $folderParent->id_folder : $model->id_folder,// parent folder id or current folder's id
            'folderTranslations' => $folderTranslations
        ]);
    }

    /**
     * Update translation for id_folder
     * @param type $id value of field 'docs_tree'.'id_folder'
     * @param type $lang
     * @return type
     */
    public function actionUpdateTranslation($id, $lang)
    {
        $model = $this->findMediaTrModel($id, $lang);
        if (!$model){
            $model = new DocsTreeTr();
            $model->id_folder = $id;
            $model->lang = $lang;
        }

        if($model->load(Yii::$app->request->post())) {
            $model->scenario = 'create';

            if($model->validate()){
                if($model->save(false)) {
                    //Yii::$app->session->setFlash('success', 'Model has been saved');
                    Yii::trace('model docstree updated:'.print_r($model->getAttributes(),true));
                }
                else {
                    //Yii::$app->session->setFlash('error', 'Model could not be saved');
                    Yii::trace('ERROR! model docstree update failed:'.print_r($model->errors,true));
                }
            }
            else {
                Yii::trace("Validation docstree error: " . print_r($model->errors, true));
            }
        }
        return $this->redirect(['update', 'id' => $id]);
    }

    /**
     * Delete media by primary key $id
     * and delete related media translation models via Media::beforeDelete()
     * @param $id value of database field 'id_media'
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if($model) $model->delete();

        return $this->redirect(['main/list']);
    }


    public function actionDeleteTranslation($id, $lang)
    {
        $model = $this->findMediaTrModel($id, $lang);
        if ($model) $model->delete();

        return $this->redirect(['update', 'id' => $id]);
    }

    /** Find Folder model by primary key $id
     * @param $id value of database field 'id_media'
     * @throws \yii\web\NotFoundHttpException
     */
    protected function findModel($id)
    {
        if (($model = DocsTree::findOne($id)) !== null) {
            return $model;
        } else {
            throw new \yii\web\NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Find Folder's translation
     * @param $folderId
     * @param $lang
     * @return array|bool|null|\yii\db\ActiveRecord
     */
    protected function findMediaTrModel($folderId, $lang)
    {
        if(($modelDocsTreeTr = DocsTreeTr::find()->where(['id_folder' => $folderId, 'lang' => $lang])->one()) !==null) {
            return $modelDocsTreeTr;
        }
        return false;
    }

    /**
     * Update translation for id_media
     * @param type $id value of field 'media'.'id_media'
     * @param type $lang
     * @return type
     */
/*s
    public function actionUpdateTranslation($id, $lang)
    {
        $model = $this->findMediaTrModel($id, $lang);
        if (!$model){
            $model = new MediaTr();
            $model->id_media = $id;
            $model->lang = $lang;
        }

        if($model->load(Yii::$app->request->post())) {
            if($model->type == 'gallery') $model->scenario = 'create-gallery';
            else $model->scenario = 'create';

            if($model->validate()){
                if($model->save(false)) {
                    //Yii::$app->session->setFlash('success', 'Model has been saved');
                    Yii::trace('we update or save mediaTR:'.print_r($model->getAttributes(),true));
                }
                else {
                    //Yii::$app->session->setFlash('error', 'Model could not be saved');
                    Yii::trace('ERROR! update or save mediaTR:'.print_r($model->errors,true));
                }
            }
            else {
                Yii::trace("Errors when save model Tr: " . print_r($model->errors, true));
            }
        }
        return $this->redirect(['update', 'id' => $id]);
    }
*/


    /**
     * Generate data for form in Modal with medias for moving
     * @param type $id
     * @return type
     */
    public function actionMoveFiles($id,$type)
    {
        $model = \app\modules\documents\models\DocsTree::findOne(['id_folder' => $id]);

        $typesArray = SearchRepositoryFiles::getMimetypesByType($type);
        $typesArray[] = $type; //contains mime-types and GET type

        $mediaAll = Media::find()
            ->joinWith('mediaLinks')
            ->where(['context' => 1])
            ->andWhere(['type' => $typesArray])
            ->asArray()->all(); // all available media

        $mediaInFolder = Media::find()
            ->joinWith('mediaLinks')
            ->where(['id_container' => $id])
            ->andWhere(['context' => 1])
            ->andWhere(['type' => $typesArray])
            ->asArray()->all(); //media in current folder

        $items = [];
        $selection = [];

        foreach ($mediaAll as $media) {
            $items[$media['id_media']] = $media['name'];
        }
        foreach ($mediaInFolder as $mediaFolder) {
            $selection[$mediaFolder['id_media']] = $mediaFolder['name'];
        }

        return $this->renderAjax('_moveFiles', [
            'model' => $model,
            'items' => $items,
            'selection' => $selection,
        ]);
    }

    /**
     * Save moved files (from modal)
     * @return type
     */
    public function actionSaveMovedFiles()
    {
        $postData = Yii::$app->getRequest()->post();

        $idFolder = $postData['DocsTree']['id_folder'];
        $errors = [];

        $mediaInFolderBefore = Media::find()->joinWith('mediaLinks')->where(['id_container' => $idFolder])->andWhere(['context' => 1])->all();
        $mediaInFolderAfter = (isset($postData['multiForm'])) ? $postData['multiForm'] : [];

        foreach ($mediaInFolderBefore as $mediaBefore) {

modules/documents/views/folder/_createForm.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>

<?php $form = ActiveForm::begin(['id' => 'create-folder', 'options' => ['class' => 'create-update-folder', 'role' => 'form']]); ?>
<?= $form->field($model, 'lang')->hiddenInput(['value' => 'default'])->label(false)  ?>
<h3>Add meta</h3>

<div class="form-group">
<?= $form->field($model, 'label')->textInput(['placeholder' => 'Enter your label'])->label('Folder title') ?>
</div>
<div class="form-group">
<?= $form->field($model, 'description')->textInput(['placeholder' => 'Enter Short Description'])->label('Short Description') ?>
</div>

<?php 
$iconCurrent = '';
if($model->icon!='') {
    $iconCurrent = $model->icon; // for load current custom image value on radio value
    $model->icon = 'custom';
}
?>
<?php
echo $form->field($model, 'icon', [
    'inline' => true,
 //'enableLabel' => false
])->radioList([
    '' => 'Standard Icon',
    'custom' => 'Custom image'
], [
    'id' => 'icon_block',
    'class' => 'form-group',
    //'data-toggle' => 'buttons',
    //'unselect' => null, // remove hidden field
    'item' => function ($index, $label, $name, $checked, $value) use($iconCurrent) {
        if ($value == 'custom') {
            return "<label><a type=\"button\" data-toggle=\"collapse\" data-target=\"#collapseExample\" aria-expanded=\"false\"
                           aria-controls=\"collapseExample\">" . Html::radio($name, $checked, ['id' => "radio_custom", 'value' => ($iconCurrent != '') ? $iconCurrent : $value, 'class' => 'project-status-btn']) . $label . "</a></label>";
        } else {
            return "<label>" . Html::radio($name, $checked, ['id' => "radio_standard", 'value' => $value, 'class' => 'project-status-btn']) . $label . "</label>";
        }
    },
]);
?>



<div class="collapse out" id="collapseExample">
    <div class="upload-drop-zone" id="drop-zone-icon">
        <?php
        echo \kato\DropZone::widget([
            'id' => 'iconUploader',
            'dropzoneContainer' => 'iconUploader',
            'previewsContainer' => 'previewsIcon',
            'options' => [
                'dictDefaultMessage' => 'Drag and drop 100 x 100 icon here',
                'url' => '/documents/document/upload?id_folder=' . $idContainer,
                'maxFilesize' => '2', // to config
                'maxFiles' => '1', // to array map config
                'acceptedFiles' => 'image/*', // to array map config
            ],
            'clientEvents' => [
                'complete' => "function(file){console.log(file); eventAfterIconUpload(file);}",
                'removedfile' => "function(file){alert(file.name + ' is removed')}"
            ],
        ]);
        ?>
    </div>
</div>
<?php ActiveForm::end(); ?>

modules/documents/views/folder/_createTranslationForm.php
<?php

use yii\bootstrap\ActiveForm;

$formVar = 'form' . $key;
?>

<?php $$formVar = ActiveForm::begin([
    'id' => 'create-folderTr-' . $key,
    'action' => ['update-translation', 'id' => $folder->id_folder, 'lang' => $key],
    'options' => ['class' => 'create-update-media', 'role' => 'form']
    ]); ?>
<?= $$formVar->field($model, 'lang')->hiddenInput(['value' => $key])->label(false); ?>
<h3>Add meta</h3>

<div class="form-group">
<?= $$formVar->field($model, 'label')->textInput(['placeholder' => 'Enter your name'])->label('File name') ?>
</div>

<div class="form-group">
<?= $$formVar->field($model, 'description')->textInput(['placeholder' => 'Enter Short Description'])->label('Short Description') ?>
</div>

<?php ActiveForm::end(); ?>

modules/documents/views/folder/_moveFiles.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<div class="row">
    <div id="success"> </div> <!-- For success message -->
</div>

<div class="row">   
    <?php $form = ActiveForm::begin(['options' => ['class' => 'moveFiles', 'id' => 'formMoveFiles']]); ?>
    <div class="row">
        <div class="col-md-offset-3">
            <?= Html::listBox('multiForm', array_keys($selection), $items, ['multiple' => true, 'class' => 'searchable']); ?>
        </div>  
    </div>
    <?= $form->field($model, 'id_folder')->hiddenInput(['value' => $model->id_folder])->label(false); ?>
    <?php ActiveForm::end(); ?>
</div>
<?php
$this->registerJs('
$(\'.searchable\').multiSelect({
  selectableHeader: "<input type=\'text\' class=\'search-input\' autocomplete=\'off\' placeholder=\'enter name\'>",
  selectionHeader: "<input type=\'text\' class=\'search-input\' autocomplete=\'off\' placeholder=\'enter name\'>",
  afterInit: function(ms){
    var that = this,
        $selectableSearch = that.$selectableUl.prev(),
        $selectionSearch = that.$selectionUl.prev(),
        selectableSearchString = \'#\'+that.$container.attr(\'id\')+\' .ms-elem-selectable:not(.ms-selected)\',
        selectionSearchString = \'#\'+that.$container.attr(\'id\')+\' .ms-elem-selection.ms-selected\';

    that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
        .on(\'keydown\', function(e){
            if (e.which === 40){
                that.$selectableUl.focus();
                return false;
            }
        });

    that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
        .on(\'keydown\', function(e){
            if (e.which == 40){
                that.$selectionUl.focus();
                return false;
            }
        });
  },
  afterSelect: function(){
    this.qs1.cache();
    this.qs2.cache();
},
  afterDeselect: function(){
    this.qs1.cache();
    this.qs2.cache();
}
//});
});

$(\'.ms-container\').css(\'width\', \'500px\');
    //});', \yii\web\View::POS_READY);

modules/documents/views/folder/bulk.php
<?php
/* @var $this yii\web\View */
use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\DetailView;

$this->title = 'Documents';
$this->params['breadcrumbs'][] = ['label' => $this->title, 'url' => ['main/index']];

if($model->father->id_folder != $model->id_folder) { // folder has parent folder
    $this->params['breadcrumbs'][] = [
        'label' => $model->father->label, 
        'url' => ['main/index', 'id_folder'=>$model->father->id_folder]
    ];
}
$this->params['breadcrumbs'][] = ['label' => $model->label];

$dataProviderMediaAll->sort->sortParam = 'media-all-sort';

$dataProviderMediaCur->sort->sortParam = 'media-cur-sort';
?>
<h1>Documents</h1>
<p class="lead">Manage your Docs and Folders</p>

<hr>
<div class="row">
<div class="col-md-6">
    <?= GridView::widget([
        'dataProvider' => $dataProviderMediaAll,
        'filterModel' => $searchModelNotCurrent,
        'tableOptions' => [
            'class' => 'table table-striped  table-condensed'
        ],
        'columns' => [
            [
                'class' => 'yii\grid\CheckboxColumn',
                'checkboxOptions' => function ($model, $key, $index, $column) {
                    $key=$model['id_media'];
                    Yii::trace('checkbox key'.print_r($key,true));
                    return [
                        'onclick' =>"console.log('clicked:'+this.checked);",
                        'value'=> $model['id_media']
                    ];//['data-uid' => $model->user_id, 'data-jid'=>$model->job_id];
                }

            ],
            'name',
            'type'
        ],

        //'summary' => 'Displaying {begin}-{end} of {totalCount} results', //Displaying 1-12 of 24 results
        'layout' => '{items}',
    ])
    ?>
    <div class="pull-right">
        <?=yii\bootstrap\Button::widget([
            'label' => 'Add selected',
            'options' => [
                'id' => 'addButton',
                'class' => 'bulk-actions-btn btn btn-success btn-small',
                'disabled' => false
            ],
        ]);?>
    </div>
</div>

<div class="col-md-6">
    <?= GridView::widget([
        'dataProvider' => $dataProviderMediaCur,
        'filterModel' => $searchModelCurrent,
        'tableOptions' => [
            'class' => 'table table-striped  table-condensed'
        ],
        'columns' => [
            [
                'class' => 'yii\grid\CheckboxColumn',
                'checkboxOptions' => function ($model, $key, $index, $column) {
                    return [
                        'onclick' =>"console.log('clicked:'+this.checked);",
                    ];//['data-uid' => $model->user_id, 'data-jid'=>$model->job_id];
                }
            ],
            'name',
            'type'
        ],

        //'summary' => 'Displaying {begin}-{end} of {totalCount} results', //Displaying 1-12 of 24 results
        'layout' => '{items}',
    ])
    ?>
    <!--<input type="button" class="btn btn-info" value="Multiple Delete" id="MyButton" >-->
    <div class="pull-right">
    <?=yii\bootstrap\Button::widget([
        'label' => 'Remove selected',
        'options' => [
            'id' => 'removeButton',
            'class' => 'bulk-actions-btn btn btn-danger btn-small',
            'disabled' => false
        ],
    ]);?>
    </div>
</div>

<?php

$this->registerJs('

    $(document).ready(function(){
    $(\'#addButton\').click(function(){

        var keys = $(\'#w0\').yiiGridView(\'getSelectedRows\');
        var mediaChecked = [];
        keys.forEach(function(entry) {
            var dataKey = \'[data-key=\'+entry+\']\';
            mediaChecked.push($(dataKey).find("input[type=checkbox]").val());
        });
        //console.log(mediaChecked);

          $.ajax({
            type: \'POST\',
            url : \'multiple-add\',
            data : {row_id: mediaChecked,folder_id:'.$model->id_folder.'},
            success : function() {
              $(this).closest(\'tr\').remove(); //or whatever html you use for displaying rows
            }
        });

    });


    $(\'#removeButton\').click(function(){

        var HotId = $(\'#w1\').yiiGridView(\'getSelectedRows\');
          $.ajax({
            type: \'POST\',
            url : \'multiple-delete\',
            data : {row_id: HotId,folder_id:'.$model->id_folder.'},
            success : function() {
              $(this).closest(\'tr\').remove(); //or whatever html you use for displaying rows
            }
        });

    });
    });', \yii\web\View::POS_READY);

?>

modules/documents/views/folder/create.php
<?php

use yii\helpers\Html;
//use yii\widgets\ActiveForm;
use yii\bootstrap\ActiveForm;
use yii\widgets\Pjax;
use yii\grid\GridView;

$this->title = 'Documents';

$this->params['headerTitle'] = "Documents Folder \"{$model->label}\" Create/update";
$this->params['headerDescription'] = "Use List view to show only documents in a sortable list .";

$this->title = 'Documents';
$this->params['breadcrumbs'][] = ['label' => $this->title, 'url' => ['main/list']];

$parents = $model->parents()->all();
foreach ($parents as $parentFolder) {
    $this->params['breadcrumbs'][] = [
        'label' => $parentFolder->label,
        'url' => ['folder/view', 'id' => $parentFolder->id_folder]
    ];
}

$this->params['breadcrumbs'][] = [
    'label' => ($model->label) ? $model->label : 'Folder name',
    'template' => "<li><b>{link}</b></li>\n"
];

?>

    <div class="col-md-3">
        <div class="hpanel panel-group">
            <div class="panel-body">
                <div class="text-center text-muted font-bold">Select translation or add new</div>

            </div>
            <div class="panel-section">

                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Select Area...">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button"><i
                            class="glyphicon glyphicon-plus small"></i></button>
                </span>
                </div>
                <button type="button" data-toggle="collapse" data-target="#notes"
                        class="btn-sm visible-xs visible-sm collapsed btn-default btn btn-block m-t-sm">
                    All notes <i class="fa fa-angle-down"></i>
                </button>
            </div>

            <div id="notes" class="collapse">
                <div class="panel-body note-link active_contact_side_bar">
                    <a href="#default" data-toggle="tab">
                        <small class="pull-right text-muted">WORLD</small>
                        <h5>Default</h5>

                        <div class="small">
                            <strong><?= $model->label ?></strong>
                        </div>
                        <div class="small">
                            <?= $model->description ?>
                        </div>
                    </a>
                </div>

                <?php foreach ($folderTranslations as $key => $languageRelation): ?>
                    <div class="panel-body note-link <?php if (!$model->id_folder) echo 'disabledTab'; ?>">
                        <a href="#<?= $key ?>" data-toggle="tab">
                            <small
                                class="pull-right text-muted"><?php if (isset($languageRelation['country'])) echo $languageRelation['country']; ?></small>
                            <h5><?php if (isset($languageRelation['language'])) echo $languageRelation['language'] ?></h5>

                            <div class="small">
                                <strong><?= $languageRelation['model']->label; ?></strong>
                            </div>
                            <div class="small">
                                <?= $languageRelation['model']->description; ?>
                            </div>
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>

    <div class="col-md-9">
        <div class="hpanel">

            <div class="panel-body">

                <div class="text-center hidden">
                    We couldn't find any Document. Add one
                </div>

                <div class="tab-content">
                    <div id="default" class="tab-pane active">
                        <div class="pull-right text-muted m-l-lg">
                            WORLD
                        </div>
                        <h3>Default</h3>
                        <hr/>
                        <div class="note-content">
                            <div class="row">
                                <div class="col-lg-12">
                                    <?=
                                    $this->render('_createForm', [
                                        'model' => $model,
                                        'idContainer' => $idContainer,
                                    ]);
                                    ?>
                                </div>
                            </div>

                        </div>

                        <?php $formDelete = ActiveForm::begin(['id' => 'delete-folder', 'method' => 'GET', 'action' => ['delete']]); ?>
                        <?= Html::hiddenInput('id', $model->id_folder); ?>
                        <?php ActiveForm::end(); ?>

                        <div class="btn-group">
                            <button class="btn btn-sm btn-default" form="create-folder"><i
                                    class="fa fa-thumbs-o-up"></i> Save
                            </button>
                            <button class="btn btn-sm btn-default" form="delete-folder"><i class="fa fa-trash"></i>
                                Remove
                            </button>
                        </div>
                    </div>


                    <?php foreach ($folderTranslations as $key => $languageRelation): ?>
                        <div id="<?= $key ?>" class="tab-pane">
                            <div class="pull-right text-muted m-l-lg">
                                <?= $languageRelation['country'] ?>
                            </div>
                            <h3><?= $languageRelation['language'] ?></h3>
                            <hr/>
                            <div class="note-content">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <?=
                                        $this->render('_createTranslationForm', [
                                            'key' => $key,
                                            'folder' => $model,
                                            'model' => $languageRelation['model'],
                                        ]);
                                        ?>
                                    </div>
                                </div>

                            </div>
                            <?php $formDelete = ActiveForm::begin(['id' => "delete-folderTr-{$key}", 'method' => 'GET', 'action' => ['delete-translation', 'id' => $model->id_folder, 'lang' => $key]]); ?>
                            <?= Html::hiddenInput('id', $model->id_folder); ?>
                            <?php ActiveForm::end(); ?>

                            <div class="btn-group">
                                <button class="btn btn-sm btn-default" form="create-folderTr-<?= $key ?>"><i
                                        class="fa fa-thumbs-o-up"></i> Save
                                </button>
                                <button class="btn btn-sm btn-default" form="delete-folderTr-<?= $key ?>"><i
                                        class="fa fa-trash"></i>
                                    Remove
                                </button>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>

            </div>

        </div>
    </div>

<?php
$js = <<<JS
/* bind clicks on the labels */
/*$('#icon_block').find('label').click(function(e) {
    //e.preventDefault();
    console.log(this);
    $(this).closest('.note-content').find('.create-update-media').yiiActiveForm('validateAttribute', 'icon_block');
});
*/
// event after upoading icon image
function eventAfterIconUpload(file){
$('#radio_custom').val(file.name);
//$('#create-media').yiiActiveForm('validateAttribute', 'icon_block'); // before
$('#icon_block').closest('.note-content').find('.create-update-folder').yiiActiveForm('validateAttribute', 'icon_block'); // validate Icon radio input after uploading
}

// active current language in tranlsation block
$(document).ready(function(){
    $('.note-link').click(function() {
        $(this).addClass('active_contact_side_bar').siblings().removeClass('active_contact_side_bar');
    });
});
JS;

$this->registerJs($js, \yii\web\View::POS_READY); //, 'projects-filter-form-script'
?>