modules/documents/controllers/MainController.php
<?php

namespace app\modules\documents\controllers;

use app\modules\documents\models\DocsTree;
use app\modules\documents\models\Media;
use app\modules\documents\models\SearchRepositoryFiles;
use yii\data\ArrayDataProvider;
use yii\web\Controller;
use dosamigos\arrayquery\ArrayQuery;
use yii\helpers\Html;
use Yii;

/**
 * Default controller for module 'Documents'
 */
class MainController extends Controller
{

    public $defaultAction = 'list';
    public static $nestedFolders; //array of nested folders
    public static $relationArray;
    public static $modalContentUri = 'folder/move-files'; //uri for content into Modal (click Massive move button)

    public function init()
    {
        self::$relationArray = [];
    }

    /**
     * @var array list of items (folder, files) and options
     * - icon: icon's style
     * - label: string, optional, specifies the menu item label.
     * - urlNew: array, optional, specifies the URL for creating new item. It will be processed by [[Url::to]].
     */
    public $entities = [
        'folder' => [
            'icon' => 'fa fa-folder-o',
            'label' => 'Folder',
            'urlNew' => ['folder/create'],
        ],
        'pdf' => [
            'icon' => 'fa fa fa-file-pdf-o',
            'label' => 'Pdf',
            'urlNew' => ['document/create', 'type'=>'pdf'],
        ],
        'movie' => [
            'icon' => 'fa fa-file-movie-o',
            'label' => 'Movie',
            'urlNew' => ['document/create', 'type'=>'movie'],
        ],
        'html5' => [
            'icon' => 'fa fa-file-code-o',
            'label' => 'HTML5',
            'urlNew' => ['document/create', 'type'=>'html5'],
        ],
        'gallery' => [
            'icon' => 'fa fa-file-image-o',
            'label' => 'gallery',
            'urlNew' => ['document/create', 'type'=>'gallery'],
        ],
        'powerpoint' => [
            'icon' => 'fa fa-file-powerpoint-o',
            'label' => 'PowerPoint',
            'urlNew' => ['document/create', 'type'=>'powerpoint'],
        ],
        'excel' => [
            'icon' => 'fa fa-file-excel-o',
            'label' => 'Excel',
            'urlNew' => ['document/create', 'type'=>'excel'],
        ],
        'word' => [
            'icon' => 'fa fa-file-word-o',
            'label' => 'Word',
            'urlNew' => ['document/create', 'type'=>'word'],
        ],
        'default' => [
            'icon' => 'fa fa-file',
            'label' => 'File',
            'urlNew' => ['document/create', 'type'=>'file'],
        ],
    ];

    /**
     * Constuct list datatable
     * @return type
     */
    public function actionList()
    {
        //apply filters
        if (Yii::$app->getRequest()->getQueryParam('sharable') || Yii::$app->getRequest()->getQueryParam('type')) {
            $documents = DocsTree::find()
            ->joinWith('media.repositoryFile')
            ->orderBy(['zse_v1_docs_tree.id_folder' => SORT_ASC])->limit(10000);

            $modelsProvider = [];
            foreach ($documents->all() as $folder) {
                $sizeFolder = 0;
                $countSharable = [
                    0 => 0, //count not sharable files in folder
                    1 => 0 //count sharable files in folder
                ];
                if (isset($folder->media)) {
                    foreach ($folder->media as $media) {
                        if ($this->mediaAlreadyExists($modelsProvider, "id", $media->id_media, $media->type))
                            continue; //if media allready in array (earlier added from another linked folder)

                        if (isset($media->repositoryFile)) { //calculate size for this media
                            $modelsProvider[] = $this->parseFile($media);
                            $sizeFolder += $media->repositoryFile->size;
                        } elseif ($media->type === 'gallery') { //calculate size for gallery item
                            $galleryItems = explode("\n", $media->multimedia);
                            $gallerySize = 0;
                            foreach ($galleryItems as $item) {
                                $itemSize = \app\modules\documents\models\RepositoryFiles::find()->select('size')->where(['name' => $item])->scalar();
                                $sizeFolder += $itemSize;
                                $gallerySize += $itemSize;
                            }
                            $modelsProvider[] = $this->parseFile($media, $gallerySize);
                        }
                        $countSharable[$media->cansend] ++;
                    }
                }

                $modelsProvider[] = $this->parseFolder($folder, $sizeFolder, $countSharable);
            }

            //check "Type" filter
            if (Yii::$app->getRequest()->getQueryParam('type')) {
                $filterType = $this->getFilterType(Yii::$app->getRequest()->getQueryParam('type'));
            }

            if (count($modelsProvider) > 0) {
                $query = new ArrayQuery($modelsProvider);
                if ($filterType)
                    $query->addCondition('type', $filterType['value']); //apply type filter
                if (Yii::$app->getRequest()->getQueryParam('sharable'))
                    $query->addCondition('sharable', 1); //apply sharable filter

                $modelsProvider = $query->find();
            }
        } else { //get array of nested folders and medias (default action (without filters))
            $folderId = (Yii::$app->getRequest()->getQueryParam('id_folder')) ? Yii::$app->getRequest()->getQueryParam('id_folder') : 0;
            $currentFolder = ($folderId > 0) ? DocsTree::findOne(['id_folder' => $folderId]) : DocsTree::find()->roots()->one(); //for one folder in root
            $modelsProvider = $this->getNestedList($currentFolder);
        }

        $provider = new ArrayDataProvider([
            'allModels' => $modelsProvider,
            'sort' => [
                'attributes' => ['icon', 'name', 'type', 'sharable', 'size'],
            ],
        ]);

        return $this->render('list', [
            'folder' => isset($currentFolder) ? $currentFolder : false,
            'newEntities' => isset($currentFolder) ? $this->parseNewEntities($currentFolder) : $this->parseNewEntities(),//items for dropdown list (button NEW) -> only inside folder!!!
            'dataProvider' => $provider,
        ]);
    }

    /**
     * Set image icon (if isset)
     * @param type $image
     * @return type
     */
    public function setImgIcon($image)
    {
        return Html::img(Yii::getAlias('@web') . '/images/' . $image, ['width' => '64px', 'height' => '64px']);
        //Html::img(Yii::getAlias('@web').'/images/'. $data['image']
    }

    /**
     * Set icon style by item's type
     * @param type $type
     * @param type $addClass add class name to current name
     * @return type
     */
    public function setStyleIcon($type, $addClass = null)
    {
        $classStyle = (isset($this->entities[$type]['icon'])) ? $this->entities[$type]['icon'] : $this->entities['default']['icon'];
        if ($addClass)
            $classStyle .= ' ' . $addClass;
        return "<i class='{$classStyle}'></i>";
    }

    /**
     * Get nested list of folders and media (filters don't applied)
     *
     * @param $currentFolder DocsTree Object 
     * @return array
     */
    public function getNestedList($currentFolder, $addIconStyle = null)
    {
        $queryChildrenFolders = $currentFolder->children(1); //only children 1-st level

        $folderChildren = $queryChildrenFolders->all(); //subfolders for current folder
        $modelsProvider = []; //models array for provider
        $index = 0; //key for array $modelsProvider
        foreach ($folderChildren as $folder) {
            $modelsProvider[$index] = [
                'icon' => (is_null($addIconStyle)) ? $this->setStyleIcon('folder') : $this->setStyleIcon('folder', $addIconStyle),
                'id' => $folder->id_folder,
                'name' => $folder->label,
                'type' => 'folder',
                'sharable' => $folder->sharable,
                'size' => $folder->size,
            ];
            $index++;
        }

        if ($currentFolder) {
            $queryMedias = Media::find()
            ->joinWith('mediaLinks')
            ->joinWith('repositoryFile')
            ->andWhere(['zse_v1_media_links.id_container' => $currentFolder->id_folder])
            ->orderBy(['zse_v1_media_links.weight' => SORT_DESC, 'zse_v1_media_links.id_media' => SORT_DESC])->limit(10000);

            $mediaInFolder = $queryMedias->all(); //medias in current folder
            foreach ($mediaInFolder as $media) {
                $modelsProvider[$index] = [
                    'icon' => (is_null($addIconStyle)) ? $this->setStyleIcon($media->type) : $this->setStyleIcon($media->type, $addIconStyle), //$this->setStyleIcon($media->type),
                    'id' => $media->id_media,
                    'name' => $media->name,
                    'type' => $media->type,
                    'sharable' => $media->cansend,
                    'size' => ($media->repositoryFile) ? $media->repositoryFile->size : 0,
                    'repFile' => ($media->repositoryFile) ? $media->repositoryFile->name : null,
                ];
                $index++;
            }
        }
        return $modelsProvider;
    }

    /**
     * Parse folder for list datatable
     * @param type $folderObject
     * @param type $size
     * @param type $sharable
     * @return type
     */
    public function parseFolder($folderObject, $size, $sharable)
    {
        return [
            'icon' => ($folderObject->icon != '') ? $this->setImgIcon($folderObject->icon) : $this->setStyleIcon('folder'),
            'id' => $folderObject->id_folder,
            'name' => $folderObject->label,
            'type' => 'folder',

modules/documents/controllers/MediaLinksController.php
<?php

namespace app\modules\documents\controllers;

use Yii;
use app\modules\documents\models\MediaLinks;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * MediaLinksController implements the CRUD actions for MediaLinks model.
 */
class MediaLinksController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all MediaLinks models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => MediaLinks::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single MediaLinks model.
     * @param integer $id_media
     * @param integer $id_container
     * @param integer $context
     * @return mixed
     */
    public function actionView($id_media, $id_container, $context)
    {
        return $this->render('view', [
            'model' => $this->findModel($id_media, $id_container, $context),
        ]);
    }

    /**
     * Creates a new MediaLinks model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new MediaLinks();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id_media' => $model->id_media, 'id_container' => $model->id_container, 'context' => $model->context]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing MediaLinks model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id_media
     * @param integer $id_container
     * @param integer $context
     * @return mixed
     */
    public function actionUpdate($id_media, $id_container, $context)
    {
        $model = $this->findModel($id_media, $id_container, $context);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id_media' => $model->id_media, 'id_container' => $model->id_container, 'context' => $model->context]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing MediaLinks model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id_media
     * @param integer $id_container
     * @param integer $context
     * @return mixed
     */
    public function actionDelete($id_media, $id_container, $context)
    {
        $this->findModel($id_media, $id_container, $context)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the MediaLinks model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id_media
     * @param integer $id_container
     * @param integer $context
     * @return MediaLinks the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id_media, $id_container, $context)
    {
        if (($model = MediaLinks::findOne(['id_media' => $id_media, 'id_container' => $id_container, 'context' => $context])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/documents/views/main/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PostSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="post-search">
    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?php //$form->field($model, 'searchstring') ?>



    <div class="form-group">
        <?= Html::submitButton('Искать', ['class' => 'btn btn-primary']) ?>
        <?= Html::submitButton('Сбросить', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

modules/documents/views/main/documentsMenu.php
<div class="panel-body">
    <div class="dropdown">
        <a class="dropdown-toggle btn btn-success btn-block <?php if(!$this->params['newEntities']) echo 'disabled'; ?>" href="#" data-toggle="dropdown">
            NEW
        </a>

        <?php
        echo yii\widgets\Menu::widget([
            'encodeLabels' => false,
            'options' => [
                'class' => 'dropdown-menu filedropdown m-l',
            ],
            'items' => ($this->params['newEntities']) ? $this->params['newEntities'] : [],
        ]);
        ?>
    </div>

    <?php echo yii\bootstrap\Nav::widget([
        'options' => ['class' => 'h-list m-t'],
        'encodeLabels' => false,
        'items' => [
            [
                'label' => '<i class="fa fa-list"></i> List',
                'url' => ['main/list'],
            ],
            [
                'label' => '<i class="fa fa-folder"></i> Folders',
                'url' => ['main/folders'],
            ],
            [
                'label' => '<i class="fa fa fa-th"></i> Flow',
                'url' => ['main/flow'],
            ]
        ],
    ]);
    ?>
</div>

modules/documents/views/main/flow.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = 'Flow views';

// module root
$this->params['breadcrumbs'][] = [
    'label' => "Documents",
    'url' => ['']
];


if (isset($folder['id_folder']) && $folder['id_folder'] > 0) {
    $this->params['breadcrumbs'][] = ['label' => $this->title, 'url' => ['main/flow']];

    $parents = $folder->parents()->all();
    foreach ($parents as $parentFolder) {
        $this->params['breadcrumbs'][] = [
            'label' => $parentFolder->label,
            'url' => ['main/flow', 'id_folder' => $parentFolder->id_folder]
        ];
    }

    $this->params['breadcrumbs'][] = [
        'label' => $folder['label'],
        'template' => "<li><b>{link}</b></li>\n"
    ];
} else {
    $this->params['breadcrumbs'][] = $this->title;
}


$this->params['headerTitle'] = "Documents Flow View";
$this->params['headerDescription'] = "Use Folders view to show all documents in a tree .";

$this->params['newEntities'] = $newEntities; // for dropdown list on click button NEW
?>

<div class="col-md-3">
    <div class="hpanel">
        <?=
        $this->render(
            'documentsMenu.php'
        )
        ?>
    </div>
</div>

<div class="col-md-9">
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel">
                <div class="panel-body">
                    <?= $this->render(
                        'searchForm.php'
                    ) ?>
                </div>
            </div>
        </div>
    </div>

    <div class="row" id="body-result">
        <?php if (count($columns) > 0): ?>
            <?php foreach ($columns as $column): ?>
                <div class="col-md-3">
                    <?php foreach ($column as $object): ?>
                        <div class="hpanel">
                            <div class="panel-body file-body">
                                <?php
                                if ($object['type'] == 'folder') $uri = 'folder';
                                else $uri = 'document';
                                echo Html::a(
                                    $object['icon'],
                                    [$uri . '/view', 'id' => $object['id']]
                                );
                                ?>
                            </div>
                            <div class="panel-footer">
                                <?php
                                if ($object['type'] == 'folder') {
                                    echo Html::a(
                                        $object['name'],
                                        ['main/flow', 'id_folder' => $object['id']],
                                        ['style' => 'text-decoration:underline;']
                                    );
                                } else {
                                    if (isset($object['repFile'])) {
                                        echo Html::a(
                                            $object['name'],
                                            ['/uploads/' . $object['repFile']],
                                            ['style' => 'text-decoration:underline;']
                                        );
                                    } else {
                                        echo Html::tag('span', $object['name']);
                                    }
                                }

                                ?>

                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endforeach; ?>
        <?php else: ?>
            <div class="col-md-3">
                <div class="hpanel">
                    <strong>Empty folder</strong>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>

modules/documents/views/main/folders.php
<?php

$this->title = 'Folders views';

// module root
$this->params['breadcrumbs'][] = [
    'label' => "Documents",
    'url' => ['main/list']
];

$this->params['breadcrumbs'][] = $this->title;


$this->params['headerTitle'] = "Documents Folders View";
$this->params['headerDescription'] = "Use Folders view to show all documents in a tree .";

$this->params['newEntities'] = $newEntities; // for dropdown list on click button NEW

?>

    <div class="col-md-3">
        <div class="hpanel">
            <?=
            $this->render(
                'documentsMenu.php'
            )
            ?>
        </div>
    </div>

    <div class="col-md-9">
        <div class="row">
            <div class="col-lg-12">
                <div class="hpanel">
                    <div class="panel-body">
                        <?= $this->render(
                            'searchForm.php'
                        ) ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="row" id="body-result">
            <div class="hpanel">
                <div class="panel-heading hbuilt">
                    <div id="nestable-menu" class="pull-right">
                        <button type="button" data-action="expand-all" class="btn btn-default btn-xs">Expand All
                        </button>
                        <button type="button" data-action="collapse-all" class="btn btn-default btn-xs">Collapse All
                        </button>
                    </div>
                    Document Folders
                </div>


                <div class="panel-body">
                    <div class="dd" id="nestableFolders">
                        <?php
                        echo yii\widgets\Menu::widget([
                            'options' => ['class' => 'dd-list', 'tag' => 'ol'],
                            'encodeLabels' => false,
                            'submenuTemplate' => "\n<ol 'class'='dd-list'>\n{items}\n</ol>\n",
                            'labelTemplate' => "<div class='dd-nodrag'>{label}</div>",
                            'items' => $folders,
                            'itemOptions' => ['class' => 'dd-item'],
                        ]);
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>


<?php
$this->registerJsFile(Yii::$app->request->baseUrl . '/homer/js/scripts/folders_nestable.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile(Yii::$app->request->baseUrl . '/homer/js/scripts/ajax-modal-popup.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile(Yii::$app->request->baseUrl . '/homer/js/scripts/ajax-move-files.js', ['depends' => [\yii\web\JqueryAsset::className()]]);

$this->registerCssFile("/homer/js/lou-multi-select-05449b3/css/multi-select.css", [
    'depends' => [\yii\bootstrap\BootstrapAsset::className()],
]);
$this->registerJsFile(Yii::$app->request->baseUrl . '/homer/js/quicksearch/jquery.quicksearch.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile(Yii::$app->request->baseUrl . '/homer/js/lou-multi-select-05449b3/js/jquery.multi-select.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
?>

modules/documents/views/main/search.php
<?php
/* @var $this yii\web\View */
use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use yii\widgets\ListView;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

$this->title = 'Search';
$this->params['breadcrumbs'][] = ['label' => 'Documents', 'url' => ['main/index']];
$this->params['breadcrumbs'][] = ['label'=>$this->title];
?>
<h1>Documents</h1>
<p class="lead">Manage your Docs and Folders</p>

<button data-toggle="modal" data-target="#iconModal" class="btn btn-success" type="button"><i class="fa fa-plus"></i> Add Folder </button>
<button data-toggle="modal" data-target="#iconModal" class="btn btn-success" type="button"><i class="fa fa-plus"></i> Add Media</button>

<hr>

<?php if(isset($searchModel)):?>
<?php $form = ActiveForm::begin([
        'id' => 'login-form2',
        'method' => 'post',
        'action' => ['main/search'],
        'options' => [
            'class' => 'form-search pull-right',
        ],
])
?>
    <div class="input-append">
        <input type="text" name='searchstring' value="<?php if(isset($searchModel->searchstring)) echo $searchModel->searchstring;?>" class="span2 search-query">
        <button type="submit" class="btn btn-success">Search</button>
    </div>
<?php ActiveForm::end() ?>
<?php endif; ?>

<?php Yii::trace('searchModel:'.print_r($searchModel,true));?>
<?=GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'tableOptions' => [
        'class' => 'table table-striped'
    ],
    'columns' => [
        [
            'attribute'=>'name',
            'format'=>'html',
            'value' => function($model) {
                if ($model['type']=='folder') return Html::a($model['name'], ['folder/view', 'id'=>$model['id']]);
                else return Html::a($model['name'], ['document/view', 'id'=>$model['id']]);
            }
        ],
        [
            'attribute'=>'type',
            'value'=> 'type'
        ]
    ],
    'summary' => 'Displaying {begin}-{end} of {totalCount} results', 
    'layout' => '{summary}{items}{pager}',
])
?>

modules/documents/views/main/searchForm.php
<div class="input-group">
    <input class="form-control" name="search" id="search" type="text" placeholder="Search Documents.." value="">
    <div class="input-group-btn">
        <button class="btn btn-default" id="searchButton"><i class="fa fa-search"></i></button>
    </div>
</div>

<?php
$script = <<<EOD
//$('#searchButton').click(function(){
$("#search").on("input",function(e){
//console.log($('#search').val());
    $.ajax({
        url:'search',
        type:'POST',
        data:'search='+$("#search").val(),
        dataType: 'html',
        success:function(data){
            $('#body-result').html(data);
        }
    });
});

EOD;
$this->registerJs($script, \yii\web\View::POS_READY);

modules/documents/views/main/search_list.php
<?php
use yii\helpers\Html;
use fedemotta\datatables\DataTables;

?>

<div class="hpanel">
    <div class="panel-body">
        <?= DataTables::widget([
            'dataProvider' => $dataProvider,
            'tableOptions' => [
                'class' => 'table table-striped table-bordered table-hover dataTable no-footer',
            ],
            'clientOptions' => [
                'dom' => 'lftrip',
                'searching' => false,
                'paging' => true,
                'aaSorting' => [],
                //'language' => [
                //    "search" => "Search:"
                //],
                'columnDefs' => [
                    [
                        "type" => "num-html", "targets" => 0
                    ],
                    [
                        "type" => "num-html", "targets" => 3
                    ],
                    [
                        "type" => "file-size",
                        "targets" => 4
                    ],
                    [
                        "orderable" => false,
                        "targets" => -1
                    ]
                ]
            ],
            //'filterModel' => $searchModel,
            'columns' => [
                [
                    'attribute' => 'icon',
                    'format' => 'html',
                    'value' => function ($model) {
                        return $model['icon'];
                        //return Html::img(Yii::getAlias('@web').'/images/'. $data['image'], ['width' => '70px']); //for images instead icons
                    }
                ],

                [
                    //'header' => '<span class="glyphicon glyphicon-user"></span>',
                    'attribute' => 'name',
                    'format' => 'html',
                    'value' => function ($model) {
                        if ($model['type'] == 'folder') return Html::a($model['name'], ['list', 'id_folder' => $model['id']], ['class' => 'list-link']); //'nested'
                        else return $model['name'];
                    }
                ],
                'type',
                [
                    'attribute' => 'sharable',
                    'format' => 'html',
                    'value' => function ($model) {
                        switch ($model['sharable']) {
                            case 0:
                                return '<i class="fa fa-square-o"></i>';
                                break;
                            case 1:
                                return '<i class="fa fa-check-square-o"></i>';
                                break;
                            case 2:
                                return '<i class="fa fa-minus-square-o"></i>';
                                break;
                        }
                    }
                ],
                [
                    'attribute' => 'size',
                    'value' => function ($model) {
                        return ($model['size']) ? $model['size'] . ' kb' : '0 b';
                    }
                ],
                [
                    'header' => 'Actions',
                    'headerOptions' => ['class' => ''],
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{download} {view} {update} {delete}',
                    'buttons' => [
                        'view' => function ($url, $model) {
                            if ($model['type'] == 'folder') $uri = 'folder';
                            else $uri = 'document';
                            return Html::a(
                                '<span class="fa fa-eye"></span>',
                                [$uri . '/view', 'id' => $model['id']]
                            );
                        },
                        'update' => function ($url, $model) {
                            return Html::tag('span', '', ['class' => "fa fa-pencil"]);
                        },
                        'download' => function ($url, $model) {
                            return Html::tag('span', '', ['class' => "fa fa-download"]);
                        },
                        'delete' => function ($url, $model) {
                            return Html::tag('span', '', ['class' => "fa fa-trash"]);
                        },
                    ],
                ],
            ],

        ]); ?>
    </div>
</div>`